CREATE TABLE USERS (
UserID		INT(11) NOT NULL AUTO_INCREMENT,
Username	CHAR(20) NOT NULL,
Password 	CHAR(20) NOT NULL,
Email		CHAR(20) NOT NULL,
CONSTRAINT LOGIN_PRIMARY_KEY PRIMARY KEY (UserID));

CREATE TABLE USERPROFILE (
UuserID		INT(11) NOT NULL AUTO_INCREMENT,
FirstName	CHAR(20) NOT NULL,
LastName	CHAR(20) NOT NULL,
Gender		CHAR(2) NOT NULL,
Email		CHAR(20) NOT NULL,
DOB			DATE,
CONSTRAINT PROFILE_PRIMARY_KEY PRIMARY KEY (USERID));

CREATE TABLE COMMENTS (
CommentID			INT(11) NOT NULL AUTO_INCREMENT,
ParentCommentID		INT(11),
UuserID				INT(4) NOT NULL,
DateComment			DATETIME NOT NULL,
CommentText			TEXT,
CONSTRAINT COMMENTS_PRIMARY_KEY PRIMARY KEY (COMMENTID));	

CREATE TABLE SUBMISSION (
SubmissionID	INT(4) NOT NULL AUTO_INCREMENT,
WorkType		CHAR(4),
Subject			CHAR(64),
Description		TEXT,
DateUpload		DATETIME,
ItemUpload		BLOB,
CommentID		INT(11),
CONSTRAINT SUBMISSION_PRIMARY_KEY PRIMARY KEY (SUBMISSIONID),
CONSTRAINT SUBMISSION_FOREIGN_KEY FOREIGN KEY (COMMENTID) REFERENCES COMMENTS (COMMENTID));

CREATE TABLE SUBMISSIONOWNERSHIP(
SubmissionID	INT(11) NOT NULL AUTO_INCREMENT,
UserID			INT(11) NOT NULL,
CONSTRAINT SUBMISSIONOWNERSHIP_PRIMARY_KEY PRIMARY KEY (SUBMISSIONID, USERID),
CONSTRAINT SUBMISSIONOWNERSHIP_FOREIGN_KEY_1 FOREIGN KEY (SUBMISSIONID) REFERENCES SUBMISSION (SUBMISSIONID),
CONSTRAINT SUBMISSIONOWNERSHIP_FOREIGN_KEY_2 FOREIGN KEY (USERID) REFERENCES USERPROFILE (USERID));