CREATE TABLE USERS (
USERID		INT(11) NOT NULL AUTO_INCREMENT,
USERNAME	CHAR(20) NOT NULL,
PASSWORD 	CHAR(20) NOT NULL,
EMAIL		CHAR(20) NOT NULL,
CONSTRAINT LOGIN_PRIMARY_KEY PRIMARY KEY (USERID));

CREATE TABLE USERPROFILE (
USERID		INT(11) NOT NULL AUTO_INCREMENT,
FIRSTNAME	CHAR(20) NOT NULL,
LASTNAME	CHAR(20) NOT NULL,
GENDER		CHAR(2) NOT NULL,
EMAIL		CHAR(20) NOT NULL,
DOB			DATE,
CONSTRAINT PROFILE_PRIMARY_KEY PRIMARY KEY (USERID));

CREATE TABLE COMMENTS (
COMMENTID			INT(11) NOT NULL AUTO_INCREMENT,
PARENTCOMMENTID		INT(11),
USERID				INT(4) NOT NULL,
DATECOMMENT			DATETIME NOT NULL,
COMMENTTEXT			TEXT,
CONSTRAINT COMMENTS_PRIMARY_KEY PRIMARY KEY (COMMENTID));	

CREATE TABLE SUBMISSION (
SUBMISSIONID	INT(4) NOT NULL AUTO_INCREMENT,
WORKTYPE		CHAR(4),
SUBJECT			CHAR(64),
DESCRIPTION		TEXT,
DATEUPLOAD		DATETIME,
ITEMUPLOAD		BLOB,
COMMENTID		INT(11),
CONSTRAINT SUBMISSION_PRIMARY_KEY PRIMARY KEY (SUBMISSIONID),
CONSTRAINT SUBMISSION_FOREIGN_KEY FOREIGN KEY (COMMENTID) REFERENCES COMMENTS (COMMENTID));

CREATE TABLE SUBMISSIONOWNERSHIP(
SUBMISSIONID	INT(11) NOT NULL AUTO_INCREMENT,
USERID			INT(11) NOT NULL,
CONSTRAINT SUBMISSIONOWNERSHIP_PRIMARY_KEY PRIMARY KEY (SUBMISSIONID, USERID),
CONSTRAINT SUBMISSIONOWNERSHIP_FOREIGN_KEY_1 FOREIGN KEY (SUBMISSIONID) REFERENCES SUBMISSION (SUBMISSIONID),
CONSTRAINT SUBMISSIONOWNERSHIP_FOREIGN_KEY_2 FOREIGN KEY (USERID) REFERENCES USERPROFILE (USERID));